schemaVersion: 2.2.0
metadata:
  name: devspaces-mta

components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:latest
      mountSources: true
      env:
        - name: VSCODE_EXTENSIONS
          value: redhat.mta-vscode-extension
