schemaVersion: 2.2.0
metadata:
  name: devspaces-workspace

components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:latest
      mountSources: true

  - name: mta-vscode-extension
    plugin:
      id: redhat.mta-vscode-extension
