schemaVersion: 2.2.0
metadata:
  name: devspaces-mta

components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:latest
      mountSources: true
      command:
        - sh
        - -c
        - |
          code-server \
            --install-extension redhat.mta-vscode-extension && \
          sleep infinity
